### ISSUE TITLE
Detailed information about the AOD

### ISSUE THREAD

**Issue by cabooster** [songxindong/FANTASIA#2]
Hi, I'm very interested in your work about the silent two-photon microscope. Could you please tell me the manufacturer and model of the AODs. I just could not find the information in your paper. Thanks a lot!

**Comment by x-song-x** [comment]
Hi there, 
the AOD pair has beens described in the paper as "The laser scanning was controlled by a pair of AODs pre-mounted orthogonally to each other in a single enclosure (AA opto-electronic AA-DTSXY-A15-850)".
This model is a customized model (15mm aperture) that you may not directly find on their website. But you can contact the company for more information. Wish this would help a bit. 
And I see you are from Beijing. I actually have recently recolated to Beijing. You can drop me a note if you want more local discussions. 
Best,
Xindong
